name: IR Engine Dev Deployment

on:
  push:
    branches: [dev]

jobs:
  remote-dispatch-dev-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Send Remote Dispatch to Deploy Dev
        id: check-secrets-webhook
        run: |
          curl -H "Authorization: token ${{ secrets.IR_ORG_ACCESS_TOKEN }}" \
              -H 'Accept: application/vnd.github.everest-preview+json' \
              ${{ secrets.IR_ENGINE_OPS_API_URL }} \
              -d '{"event_type": "deploy-dev"}'
